# Model Training Parameters
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # [Height, Width, Channels]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01

# Data Parameters
VALIDATION_SPLIT: 0.20